# Website configuration file
project:
  type: website
  output-dir: _site

website:
  title: "SolarScape"
  navbar:
    left:
      - href: pages/proposal.qmd
        text: Proposal
      - href: pages/methodology.qmd
        text: Methodology
      - href: pages/results.qmd
        text: Results and Discussion
      - href: pages/lessons.qmd
        text: Lessons Learnt

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    
execute:
  freeze: auto
  