# Website configuration file
project:
  type: website
  output-dir: _site

website:
  title: "SolarScape"
  page-footer:
      center: "Copyright 2025, SolarScape"
  navbar:
    background: dark
    left:
      - href: index.html
        text: Overview
      - href: pages/proposal.html
        text: Proposal
      - href: pages/methodology.html
        text: Methodology
      - href: pages/results.html
        text: Results and Discussion
      - href: pages/lessons.html
        text: Lessons Learnt
      - href: pages/poster.html
        text: Poster
      - href: pages/report.html
        text: Report
    
format:
  html:
    theme: [litera,styles.scss]
    toc: true
    
execute:
  freeze: auto
  