# Website configuration file
project:
  type: website
  output-dir: _site

website:
  title: "SolarScape"
  page-footer:
      center: "Copyright 2025, SolarScape"
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Overview
      - href: pages/proposal.qmd
        text: Proposal
      - href: pages/methodology.qmd
        text: Methodology
      - href: pages/results.qmd
        text: Results and Discussion
      - href: pages/lessons.qmd
        text: Lessons Learnt
      - href: pages/poster.qmd
        text: Poster
      - href: pages/report.qmd
        text: Report
    
    

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    
execute:
  freeze: auto
  