# Website configuration file
project:
  type: website
  output-dir: _site

website:
  page-navigation: true
  site-url: "https://solarscape.netlify.app" 
  repo-url: "https://github.com/je-rnic/SMT201-GIS-Group3"
  repo-actions: [edit, source, issue]
  favicon: images/navbar-solarscape-logo2.svg

  page-footer:
      center: "Copyright 2025, SolarScape"
  navbar:
    logo: images/navbar-solarscape-logo2.svg
    background: light
    left:
      - href: pages/report.html
        text: Report
      - href: pages/methodology.html
        text: Methodology
      - href: pages/results.html
        text: Results and Discussion
      - href: pages/lessons.html
        text: Lessons Learnt
      - href: pages/poster.html
        text: Poster
      - href: geoweb/SolarScapeInteractiveMap/index.html
        text: Interactive Map
      - href: pages/meeting-minutes.html
        text: Meeting Minutes
    
format:
  html:
    theme: [litera,styles.scss]
    toc: true
    
execute:
  freeze: auto
  